#!/bin/bash

export WEAVIATE_URL="https://ai-meme-generation-9xwtq8vx.weaviate.network"
export ACCESS_TOKEN="8Jf5YQuFICsJPHaveRDwxB8h6LaIEcqqbLyq"
export OPENAI_API_KEY="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"
